### ISSUE TITLE
Loading spinner loops forever when the reflexion analysis creates new edges.

### ISSUE THREAD

**Issue by koschke** [uni-bremen-agst/SEE#722] opened 2024-04-08 14:47 UTC
The `EdgeMeshScheduler `shows a `LoadingSpinner `upon the `OnNext `event somehow triggered by the reflexion analysis.
This `LoadingSpinner `does not disappear again. Somehow, the closing of it is missing.

**Comment by falko17** [comment] 2024-10-30 20:08
I cannot reproduce this issue, I'll assume it has been fixed in the meantime.

**Closed by falko17** 2024-10-30 20:08 UTC
Labels: bug
